version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KAGGLE_USERNAME: ${env.KAGGLE_USERNAME}
        - KAGGLE_KEY: ${env.secrets.KAGGLE_KEY}
        - MONGODB_CONN_STRING: ${env.secrets.MONGODB_CONN_STRING}
    env_file:
      - .env
    ports:
      - "80:80"
