version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KAGGLE_USERNAME: ${{ KAGGLE_USERNAME }}
        - KAGGLE_KEY: ${{ KAGGLE_KEY }}
        - MONGODB_CONN_STRING: ${{ MONGODB_CONN_STRING }}
    env_file:
      - .env
    ports:
      - "80:80"
