version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      - KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      - MONGODB_CONN_STRING: ${{ secrets.MONGODB_CONN_STRING }}
    ports:
      - "80:80"
